global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'default-receiver'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - receiver: 'cpu-team'
      matchers:
        - team = cpu
      continue: true
    - receiver: 'mem-team'
      matchers:
        - team =~ "memory|cpu"


receivers:
  - name: 'default-receiver'
    slack_configs:
      - channel: '#prom-alerts'
        send_resolved: true
        text: |
          {{ range .Alerts }}
          *[DEFAULT]* {{ .Labels.alertname }} - {{ .Annotations.description }}
          {{ end }}
  - name: 'cpu-team'
    slack_configs:
      - channel: '#cpu-team'
        api_url: 'https://hooks.slack.com/services/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'
        send_resolved: true
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Labels.alertname }}
          *Description:* {{ .Annotations.description }}
          *Time:* {{ .StartsAt }}
          {{ end }}
  - name: 'mem-team'
    slack_configs:
      - channel: '#mem-team'
        api_url: 'https://hooks.slack.com/services/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'
        send_resolved: true
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Labels.alertname }}
          *Description:* {{ .Annotations.description }}
          *Time:* {{ .StartsAt }}
          {{ end }}