version: '3'

services:
  sensor-service:
    build:
      context: .
      dockerfile: ./devcontainers/sensor/Dockerfile
    ports:
      - 8081:8081
    networks:
      - local
  prom:
    image: prom/prometheus:v2.42.0
    ports:
      - 9090:9090
    networks:
      - local
    volumes:
      - ./configs/prometheus:/etc/prometheus/
    depends_on:
      - sensor-service
  alertmanager:
    image: prom/alertmanager:v0.28.0
    ports:
      - 9091:9093
    networks:
      - local
    volumes:
      - ./configs/alertmanager:/etc/alertmanager/
    depends_on:
      - sensor-service

networks:
  local: