version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    networks:
      - local
  prometheus:
    image: prom/prometheus:v2.42.0
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local
  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - 3000:3000
    networks:
      - local
    volumes:
        - ./data/grafana:/var/lib/grafana
    user: root


networks:
  local: